[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_nft_staking = "Ha25bLSF75gWeMqFtqFCzhexZh6j3fXXHeoTJYccHoLJ"
lootbox_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/chuo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
